publiclab/plotsbot

.eslintrc, bot.js, interfaces/irc.js, package.json, services/chatbot.js, utils.js
@jywarren @ryzokuken Implemented linting in this PR. Have a look and suggest if any changes are required.
=> Setup eslint and fix lint errors

services/chatbot.js
This method would hopefully help us with testing.
=> Add getResponse method to Chatbot class

package.json, spec/help-spec.js, src/behaviors/index.js
As of now, we had just one message-triggered behavior (help) which would return things instantly. Now that we are getting into making calling APIs and making database calls and whatnot, things will start taking more time. Blocking the entire bot's functioning during this process will make it struggle to work in real-life scenarios. Thus, we should use a promise based workflow. Notice here that we wrapped `Promises` around each function call to ensure that we the behavior can return their a value or a promise that resolves to a value and there will no difference using either.
=> Switch to a promise based workflow

README.md
Added the TravisCI badge below the header and above the project description in README.
=> Added a "build passing" badge to README

README.md
Added the '**license**' badge from http://shields.io to the README file as per #27
=> Added the license badge to the README file

README.md
#27  - @ryzokuken thanks for the feedback. Trying this again.
=> Added a "PRs welcome" badge to README

.travis.yml, README.md, package.json, yarn.lock
@ryzokuken, @ananyo2012  have a look at this. What are the checks and information that I need to put in ?
=> Added coveralls integration fixes #26

spec/fto-spec.js, spec/test-utils.js, src/behaviors/index.js
@jywarren @ananyo2012 tried increasing the coverage a little. Hopefully, this also makes our code a little more foolproof.
=> Add test for fto behavior covering unforeseen errors

README.md
I wasn't sure what url to link the badge to, so linked it to this : 
https://github.com/publiclab/plotsbot#dependencies
=> Added dependencies badge to readme.md

src/utils.js
@icarito looks good? Let's export this next and use it in a sample behavior. Perhaps something chatops101 style. What do you say?
=> Add a utility function for executing scripts

README.md
=> Add info about submitting behaviors

README.md, spec/utils-spec.js, src/bot.js
Made a couple small changes to get the bot running and tests passing on my machine. Based on commit history I wasn't sure if I should bother incrementing patch.
=> Minor tweaks to 1.4

package.json, src/bot.js
Should solve #80. I notice the other dependencies specify version, if 'latest' is inappropriate let me know and I can change it.
=> Added path module, updated config capture mechanism

src/bot.js
This was required to deploy the bot on tycho.
=> Switch from port 3000 to port 4000

docker-compose.yml
Now I'll setup jenkins to auto-deploy master branch.
=> Added docker-compose file. Expose to localhost:4001.

docker-compose.yml
Had the wrong path volume mounted
=> Properly link volume for local configuration

src/behaviors/greet.js
Improve the greet message, as proposed by Stevie in https://github.com/publiclab/plotsbot/issues/102
/cc @jywarren @steviepubliclab
=> Fix greet message

src/bot.js, src/models/simple-message-behavior.js
@jywarren take a look at this as soon as possible, and let's get this merged!
https://github.com/publiclab/plotsbot/compare/mini-behaviors?expand=1#diff-09b0d1ce42aaadb6154c5e9b97d4c743R40 is basically how I decided it should work, simple one-liner, feedback appreciated.
Let me know if it's fine by you, and I'll remove the sample code and everything.
=> Add support for mini-behaviors and demo it (fixes #95)

spec/behaviors-spec.js, spec/fto-spec.js, spec/help-spec.js, spec/unresponsive-spec.js, spec/version-spec.js, src/behaviors/fto.js, src/behaviors/help.js, src/behaviors/index.js
Fixes: https://github.com/publiclab/plotsbot/issues/106
cc @jywarren
=> Reorder and revamp action parameters for consistency

src/behaviors/greet.js
=> Fix buggy greet behavior

src/behaviors/greet.js, src/models/memory-behavior.js
=> Implement Memory Behaviors

src/behaviors/quiet.js, src/bot.js
Creating a behavior which auto-quiets everyone in our chatroom, except for hostmask-based exceptions we've created. 
We'll also add a way to notify all users that may not be exempted, how to request an exemption. Perhaps in the Welcome behavior. This could be a link to an email address, or a form, or something else. 
Or, we could have a send/response behavior with `plotsbot` itself to become unquieted?
@icarito @ryzokuken @pdurbin ... what do you think?
We've already exempted all Riot/Matrix users from this ban based on host mask.
=> Create quiet.js [wip, help wanted!]

src/bot.js
Needed to register with nickserv
=> Identify with nickserv if config.json has nickpass (irc)
